version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Instalando dependencias para pruebas/compilación"
      - npm install
  build:
    commands:
      - echo "Build completado"

artifacts:
  files:
    - '**/*'
